### ISSUE TITLE
12-trim实现的正则问题

### ISSUE THREAD

**Issue by coderhaoo** [qianlongo/fe-handwriting#3]
你好，return this.replace(/^\s+|\s+$/, '')应修改为 return this.replace(/^\s+|\s+$/g, '');

**Comment by qianlongo** [comment]
> 你好，return this.replace(/^\s+|\s+$/, '')应修改为 return this.replace(/^\s+|\s+$/g, '');
棒棒，谢谢你帮忙发现了这个问题，已经修复了哈
